### ISSUE TITLE
unwanted or uneven display of images behind lines of appreciation section.

### ISSUE THREAD

**Issue by Sanchali-Sharma** [sanskaromar/renaissance-2k23#40] opened 2023-02-15 07:23 UTC
![Screenshot (228)](https://user-images.githubusercontent.com/93890098/218959703-b8dbc759-f4c2-40fa-945b-169513caf2db.png)

**Comment by Ashish-Verma-MNNIT** [comment] 2023-02-15 07:38
Closing it as this issue is duplicate of issue #26

**Closed by Ashish-Verma-MNNIT** 2023-02-15 07:38 UTC
