### ISSUE TITLE
Background color difference

### ISSUE THREAD

**Issue by Cyber-Infernox** [sanskaromar/renaissance-2k23#36] opened 2023-02-14 16:55 UTC
![image](https://user-images.githubusercontent.com/97396217/218804666-d105099d-0334-471b-bc43-5439ee9728c9.png)

According to figma design... background should be of same color

**Comment by adityarai0705** [comment] 2023-02-15 11:24
<img width="844" alt="Screenshot 2023-02-15 at 4 53 16 PM" src="https://user-images.githubusercontent.com/44937487/219014275-cc5267c9-b9bf-420f-b21f-cfca323222a1.png">

Please check it again.

**Comment by adityarai0705** [comment] 2023-02-15 11:27
I have already opened an issue on this.

**Comment by Ashish-Verma-MNNIT** [comment] 2023-02-15 11:30
Closing this issue, as it is a duplicate of #27

**Closed by Ashish-Verma-MNNIT** 2023-02-15 11:30 UTC
