### ISSUE TITLE
Auth component is getting blank for small viewport and mobile view

### ISSUE THREAD

**Issue by PANDEYS432** [sanskaromar/renaissance-2k23#33] opened 2023-02-14 14:37 UTC
![Screenshot (540)](https://user-images.githubusercontent.com/98703881/218769484-f3167e5b-33be-4006-a832-f80bef3c91cf.png)
on clicking whole page gets blank for mobile view or below 640px

**Comment by samjain233** [comment] 2023-02-15 07:04
I had resolved this . Assign it to me

**Comment by Ashish-Verma-MNNIT** [comment] 2023-02-15 07:29
Closing this issue as it is a duplicate of issue #25

**Closed by Ashish-Verma-MNNIT** 2023-02-15 07:29 UTC
